services:
  db:
    image: postgres:15-alpine
    container_name: universe_db
    environment:
      POSTGRES_USER: selin_admin
      POSTGRES_PASSWORD: universe_password
      POSTGRES_DB: universe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  